# ci/pvc-wbcbench.yml - configuration for PersistentVolumeClaim for SLT data storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wbcbench-pvc
spec:
  storageClassName: rook-cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi