# ci/train-wbcbench-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: wbcbench-array
spec:
  completions: 15
  parallelism: 4
  completionMode: Indexed
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: wbcbench-array
    spec:
      restartPolicy: Never
      terminationGracePeriodSeconds: 30

      containers:
        - name: train
          image: ghcr.io/kagozi/isbi-challenge:latest
          imagePullPolicy: Always

          env:
            - name: PVC_ROOT
              value: /pvc

            # HuggingFace auth (for HOptimus1)
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: huggingface-secret
                  key: HF_TOKEN
            - name: HUGGINGFACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: huggingface-secret
                  key: HUGGINGFACE_HUB_TOKEN

            # Keep HF cache off CephFS (avoid many-small-files on PVC)
            - name: HF_HOME
              value: /pvc/cache/hf
            - name: TRANSFORMERS_CACHE
              value: /pvc/cache/hf/transformers
            - name: HF_HUB_DISABLE_TELEMETRY
              value: "1"


            # Make sure every pod knows its index (Indexed jobs expose this)
            - name: JOB_COMPLETION_INDEX
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['batch.kubernetes.io/job-completion-index']

          command: ["bash", "-lc"]
          args:
            - |
              set -euo pipefail
              nvidia-smi || true

              export PVC_ROOT=/pvc

              # Basic sanity checks
              test -d /pvc/data || (echo "❌ /pvc/data not found. Did you upload data to the PVC?" && exit 1)
              test -f /workspace/main_kfold.py || (echo "❌ /workspace/main_kfold.py not found in image." && exit 1)

              mkdir -p /pvc/outputs/logs
              cd /workspace

              echo "Running config idx: ${JOB_COMPLETION_INDEX}"
              python main_kfold.py --config_idx "${JOB_COMPLETION_INDEX}" \
                2>&1 | tee "/pvc/outputs/logs/run_${JOB_COMPLETION_INDEX}.log"

          resources:
            requests:
              nvidia.com/gpu: 1
              cpu: "4"
              memory: 16Gi
              ephemeral-storage: 20Gi
            limits:
              nvidia.com/gpu: 1
              cpu: "6"
              memory: 32Gi
              ephemeral-storage: 40Gi

          volumeMounts:
            - name: wbcbench-vol
              mountPath: /pvc

      volumes:
        - name: wbcbench-vol
          persistentVolumeClaim:
            claimName: wbcbench-pvc